#!/usr/bin/env bash
# Function to display subdomain information

print_domain_subdomain() {
	local full_domain="$1"
	local subdomain="$2"

    # Get the DNS query result
    result=$(dig +short "$full_domain")

    if [ -z "$result" ]; then
	    echo "No records found for $subdomain.$domain"
	    return
    fi

    # Get the record type
    record_type=$(dig +noall +answer "$full_domain" | awk '{print $4}' | head -n 1)

    # Output the information
    echo "The subdomain $subdomain is a $record_type record and points to $result"
}

# Check if the correct number of arguments is provided
if [ "$#" -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	print_domain_subdomain "$subdomain.$domain" "$subdomain"
else
	domain="$1"
	print_domain_subdomain "www.$domain" "www" "lb-01"
	print_domain_subdomain "lb-01.$domain" "lb-01" 
	print_domain_subdomain "web-01.$domain" "web-01" "54.146.84.100"
	print_domain_subdomain "web-02.$domain" "web-02" "100.26.167.136"
fi
