#!/usr/bin/env bash
# Function to display ssh ubuntu@8.8.8.8 -i /vagrant/sylvain 'ls ~/'

usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if correct number of arguments are passed
if [ "$#" -lt 4 ]
then
    usage
fi

# Assigning arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/
