#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# verify installation
haproxy -v


# Configure HAProxy
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  5000g

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 501207-web-01 54.146.84.100:80 check
    server 501207-web-02 100.26.167.136:80 check

sudo service haproxy restart
