#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
echo '
global
        log 127.0.0.1 local0 notice
        maxconn 2000
        user haproxy
        group haproxy

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        option redispatch
        timeout connect  5000
        timeout client  10000
        timeout server  10000

frontend alx-gaza.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 501350-web-01 35.174.200.187:80
        server 501350-web-02 54.237.102.217:80
' > /etc/haproxy/haproxy.cfg

sudo service haproxy restart