#!/usr/bin/env bash
# Replace the default server block in the Nginx configuration to listen on port 80 for all active IPv4 IPs
sudo sed -i 's/listen [::]:80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo netstat -tuln | grep ':80'
sudo systemctl stop apache2
sudo systemctl restart nginx
