#!/usr/bin/env bash
# Replace the default server block in the Nginx configuration to listen on port 80 for all active IPv4 IPs
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
