#!/usr/bin/env bash
#Write a Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

a=1
while [ $a ]; do
    echo "To infinity and beyond"
    sleep 2
done

pid=$!

# Wait for a SIGTERM signal
while true
do
  wait $pid
  if [ $? -eq 143 ]; then
      echo "I am invincible!!!"
      break
  fi
done