#!/usr/bin/env bash
#Write a Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

# Function to handle SIGTERM
handle_sigterm() 
{
    echo "I am invincible!!!"
    exit 0
}

# Set up the trap for SIGTERM
trap 'handle_sigterm' SIGTERM

a=1
while [ $a ]; do
    echo "To infinity and beyond"
    sleep 2
done