#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd.
#Your script should only display:
#username
#user id
#Home directory path for the user
passwd_file="/etc/passwd"
while IFS=: read -r username x uid gid gecos home shell; do
    echo "$username:$uid:$home"
done < "$passwd_file"