#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59
a=0

while [ "$a" -lt 13 ]; do
    echo "Hour: $a"
    b=1
    while [ "$b" -lt 60 ]; do
        echo "$b"
        ((b++))
    done
    ((a++))
done