#!/usr/bin/env bash
#script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed
for file in *; do
    without_dash=$(echo "$file" | cut -d '-' -f 2-)
    echo "$without_dash"
done