#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01

# Update package lists
sudo apt-get update

# Install ufw
sudo apt-get install ufw -y

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable

# Check ufw status
sudo ufw status
