#!/usr/bin/env bash
# Configure web-01 so that its firewall redirects port 8080/TCP to port 80/TCP

# Update package lists
sudo apt-get update

# Install ufw
sudo apt-get install ufw -y

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Add a rule to redirect port 8080 to port 80
sudo ufw route allow proto tcp from any to any port 8080 redirect to port 80

# Enable ufw
sudo ufw enable

# Check ufw status
sudo ufw status
