#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#Requirements:

#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Add custom resolution for facebook.com to /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Display the updated /etc/hosts file
cat /etc/hosts

# Restart networking to apply changes (Note: This will temporarily disconnect network connections)
sudo systemctl restart networking