#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

# Stop nginx
sudo systemctl stop nginx

# Change user in nginx.conf to nginx
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Change listen directive in default server block to listen on port 8080 and all IPs
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

sudo kill -2 11587
# Restart nginx
sudo systemctl start nginx
