#!/usr/bin/env bash
# Define server and private key file
server="ubuntu@54.209.215.201"
private_key="~/.ssh/school"

# SSH connection using single-character flags
ssh -i "$private_key" ubuntu@"$server"